name: ci-dev
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: shotgun
      additional-reports-path: ./.coverage
      additional-reports-name: coverage

  coverage:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        name: 'Fetch coverage from builds'
        with:
          name: ${{ needs.ci.outputs.additional-reports-name }}
          path: ${{ needs.ci.outputs.additional-reports-path }}

      - name: 'Convert coverage to XML report'
        shell: bash
        run: |
          coverage xml -o ./coverage.xml

      - uses: codecov/codecov-action@v3
        name: 'Upload coverage'
        with:
          fail_ci_if_error: true

